#!/bin/bash

while IFS= read -r experiment
do
    python process_results.py ../results/$experiment
done <<< $(json -f ../results/experiments.json -v "value['experiment_name']" -l)

cd ../results

git add --all ; git commit --all --message "none" ; git push

cd -